CREATE TABLE tb_post
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title   VARCHAR(255),
    content VARCHAR(255),
    user_id BIGINT,
    CONSTRAINT pk_tb_post PRIMARY KEY (id)
);

CREATE TABLE tb_user
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_tb_user PRIMARY KEY (id)
);

ALTER TABLE tb_user
    ADD CONSTRAINT uc_tb_user_username UNIQUE (username);

ALTER TABLE tb_post
    ADD CONSTRAINT FK_TB_POST_ON_USER FOREIGN KEY (user_id) REFERENCES tb_user (id);